{% set name = "ripser" %}
{% set version = "0.6.12" %}
{% set sha256 = "06a0c4ef15a95541b9b3d3d67a94e474a2876eee67235d2b2b5176b7f29e0411" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}

  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy

  run:
    - python
    - scipy
    - scikit-learn
    - persim

test:
  source_files:
    - test
  imports:
    - ripser
  requires:
    - pytest
    - numpy
  commands:
    - pytest -v test

about:
  home: http://github.com/scikit-tda/ripser.py
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Lean Persistent Homology Library for Python

  description: |
    Ripser.py is a lean persistent homology package for Python. Building on the blazing
    fast C++ Ripser package as the core computational engine, Ripser.py provides an
    intuitive interface for computing persistence cohomology of sparse and dense data sets,
    visualizing persistence diagrams, computing lowerstar filtrations on images, and computing
    representative cochains.
  doc_url: http://ripser.scikit-tda.org/
  dev_url: https://github.com/scikit-tda/ripser.py

extra:
  recipe-maintainers:
    - sauln
    - ctralie
    - bdice
