travis:
  secure:
    BINSTAR_TOKEN: scFdHlbtUXk4Jxe+xc6ndnGufbmg2As1wyaiMA52OoZgvcC/+vmFZRLyw+yTvmJ7xHRQl5YWLlTFPAFg7UYgBapY4TyE2iE/PuIU1TGNu43lB0LNfALTAqLGA+gU3nQ1R46QUhVW+6X4d7uPCvI5jO+AC+X2f8RxEUf4H+ISZ1EwT2sFEBaX+QODhZHBfcc9Q5yluZ6ClAg/qIgwrOeCz8XLynJUszcp60z49GoOnof+6GaO+/kzyLPZpeMgzEpUBQGFmorDqqTqKwNQ0iK40XichWHgiqq1Ud48ecfPTZRz8+Qa990jQso784/H6ly2J7xFeAXu6T5oLUzr1BjgsxK1Xy3Gz2zE6qEAhY0pPATrpBCXUmyZ34VWvjvARthQa1BTBFUm9qG/mUAmgzukinIGy+m7h0PmJPRkwkXqdGhV7c7py8eyA+Ya1KF0fAa77IixRUE6XsHeNBmU8Vc+56LspOKS4FlxvtutPCAHPVXa2/zAlVpCW0Eg7bLtb3UKy6rHVqWabEKoi13tNNpnPzcsNuI0/OkSlfGLA91DikiFmKKahDU24Pdua9yaNdRvTpRhPvXGh+mO6sYXv3AItkgZFfIvF0XmxdhgCyXNBkf7+VJdmzcjIs/uvkfBXo/P/udtSKUnpD+qfNYEWkA57TSvasNTiyU7Mnhi3ToY6ms=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
